#pragma once

// From glfw3.h
#define NMLS_KEY_SPACE              32
#define NMLS_KEY_APOSTROPHE         39
#define NMLS_KEY_COMMA              44
#define NMLS_KEY_MINUS              45
#define NMLS_KEY_PERIOD             46
#define NMLS_KEY_SLASH              47
#define NMLS_KEY_0                  48
#define NMLS_KEY_1                  49
#define NMLS_KEY_2                  50
#define NMLS_KEY_3                  51
#define NMLS_KEY_4                  52
#define NMLS_KEY_5                  53
#define NMLS_KEY_6                  54
#define NMLS_KEY_7                  55
#define NMLS_KEY_8                  56
#define NMLS_KEY_9                  57
#define NMLS_KEY_SEMICOLON          59
#define NMLS_KEY_EQUAL              61
#define NMLS_KEY_A                  65
#define NMLS_KEY_B                  66
#define NMLS_KEY_C                  67
#define NMLS_KEY_D                  68
#define NMLS_KEY_E                  69
#define NMLS_KEY_F                  70
#define NMLS_KEY_G                  71
#define NMLS_KEY_H                  72
#define NMLS_KEY_I                  73
#define NMLS_KEY_J                  74
#define NMLS_KEY_K                  75
#define NMLS_KEY_L                  76
#define NMLS_KEY_M                  77
#define NMLS_KEY_N                  78
#define NMLS_KEY_O                  79
#define NMLS_KEY_P                  80
#define NMLS_KEY_Q                  81
#define NMLS_KEY_R                  82
#define NMLS_KEY_S                  83
#define NMLS_KEY_T                  84
#define NMLS_KEY_U                  85
#define NMLS_KEY_V                  86
#define NMLS_KEY_W                  87
#define NMLS_KEY_X                  88
#define NMLS_KEY_Y                  89
#define NMLS_KEY_Z                  90
#define NMLS_KEY_LEFT_BRACKET       91
#define NMLS_KEY_BACKSLASH          92
#define NMLS_KEY_RIGHT_BRACKET      93
#define NMLS_KEY_GRAVE_ACCENT       96
#define NMLS_KEY_WORLD_1            161
#define NMLS_KEY_WORLD_2            162
#define NMLS_KEY_ESCAPE             256
#define NMLS_KEY_ENTER              257
#define NMLS_KEY_TAB                258
#define NMLS_KEY_BACKSPACE          259
#define NMLS_KEY_INSERT             260
#define NMLS_KEY_DELETE             261
#define NMLS_KEY_RIGHT              262
#define NMLS_KEY_LEFT               263
#define NMLS_KEY_DOWN               264
#define NMLS_KEY_UP                 265
#define NMLS_KEY_PAGE_UP            266
#define NMLS_KEY_PAGE_DOWN          267
#define NMLS_KEY_HOME               268
#define NMLS_KEY_END                269
#define NMLS_KEY_CAPS_LOCK          280
#define NMLS_KEY_SCROLL_LOCK        281
#define NMLS_KEY_NUM_LOCK           282
#define NMLS_KEY_PRINT_SCREEN       283
#define NMLS_KEY_PAUSE              284
#define NMLS_KEY_F1                 290
#define NMLS_KEY_F2                 291
#define NMLS_KEY_F3                 292
#define NMLS_KEY_F4                 293
#define NMLS_KEY_F5                 294
#define NMLS_KEY_F6                 295
#define NMLS_KEY_F7                 296
#define NMLS_KEY_F8                 297
#define NMLS_KEY_F9                 298
#define NMLS_KEY_F10                299
#define NMLS_KEY_F11                300
#define NMLS_KEY_F12                301
#define NMLS_KEY_F13                302
#define NMLS_KEY_F14                303
#define NMLS_KEY_F15                304
#define NMLS_KEY_F16                305
#define NMLS_KEY_F17                306
#define NMLS_KEY_F18                307
#define NMLS_KEY_F19                308
#define NMLS_KEY_F20                309
#define NMLS_KEY_F21                310
#define NMLS_KEY_F22                311
#define NMLS_KEY_F23                312
#define NMLS_KEY_F24                313
#define NMLS_KEY_F25                314
#define NMLS_KEY_KP_0               320
#define NMLS_KEY_KP_1               321
#define NMLS_KEY_KP_2               322
#define NMLS_KEY_KP_3               323
#define NMLS_KEY_KP_4               324
#define NMLS_KEY_KP_5               325
#define NMLS_KEY_KP_6               326
#define NMLS_KEY_KP_7               327
#define NMLS_KEY_KP_8               328
#define NMLS_KEY_KP_9               329
#define NMLS_KEY_KP_DECIMAL         330
#define NMLS_KEY_KP_DIVIDE          331
#define NMLS_KEY_KP_MULTIPLY        332
#define NMLS_KEY_KP_SUBTRACT        333
#define NMLS_KEY_KP_ADD             334
#define NMLS_KEY_KP_ENTER           335
#define NMLS_KEY_KP_EQUAL           336
#define NMLS_KEY_LEFT_SHIFT         340
#define NMLS_KEY_LEFT_CONTROL       341
#define NMLS_KEY_LEFT_ALT           342
#define NMLS_KEY_LEFT_SUPER         343
#define NMLS_KEY_RIGHT_SHIFT        344
#define NMLS_KEY_RIGHT_CONTROL      345
#define NMLS_KEY_RIGHT_ALT          346
#define NMLS_KEY_RIGHT_SUPER        347
#define NMLS_KEY_MENU               348