#pragma once

// From glfw3.h
#define NMLS_MOUSE_BUTTON_1         0
#define NMLS_MOUSE_BUTTON_2         1
#define NMLS_MOUSE_BUTTON_3         2
#define NMLS_MOUSE_BUTTON_4         3
#define NMLS_MOUSE_BUTTON_5         4
#define NMLS_MOUSE_BUTTON_6         5
#define NMLS_MOUSE_BUTTON_7         6
#define NMLS_MOUSE_BUTTON_8         7
#define NMLS_MOUSE_BUTTON_LAST      NMLS_MOUSE_BUTTON_8
#define NMLS_MOUSE_BUTTON_LEFT      NMLS_MOUSE_BUTTON_1
#define NMLS_MOUSE_BUTTON_RIGHT     NMLS_MOUSE_BUTTON_2
#define NMLS_MOUSE_BUTTON_MIDDLE    NMLS_MOUSE_BUTTON_3